# Generated by Django 5.1.2 on 2024-11-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name']},
        ),
    ]
