# Generated by Django 5.1.2 on 2024-11-09 02:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_serial', models.CharField(max_length=200)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('collect_date', models.DateField(blank=True, null=True)),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Scrapped'), (2, 'Missing'), (3, 'Sold'), (4, 'Repair')], default=0)),
            ],
            options={
                'ordering': ['item_type', 'status', 'item_serial'],
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('cost_initial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_week', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemAdmin',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
            ],
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='ItemTypeAdmin',
            fields=[
                ('itemtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.itemtype')),
            ],
            bases=('items.itemtype',),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='items.itemtype'),
        ),
    ]
