# Generated by Django 5.1.2 on 2024-11-22 11:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('sku', models.CharField(default='MH-', max_length=15, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('cost_initial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_week', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('meta_tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_serial', models.CharField(max_length=200)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('collect_date', models.DateField(blank=True, null=True)),
                ('repair_date', models.DateField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Scrapped'), (2, 'Missing'), (3, 'Sold'), (4, 'Repair')], default=0)),
                ('unique_image_field', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='items.itemtype')),
            ],
            options={
                'ordering': ['item_type', 'item_serial'],
            },
        ),
    ]
