# Generated by Django 5.1.2 on 2024-11-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='product_stripe_id',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
