# Generated by Django 5.1.2 on 2024-11-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_itemtype_sku_alter_itemtype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='meta_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
