# Generated by Django 5.1.2 on 2024-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemtype_meta_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_type', 'item_serial']},
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='item',
            name='unique_image_field',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
