# Generated by Django 5.1.2 on 2024-11-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordernote',
            options={'ordering': ['created_by'], 'verbose_name': 'Order Note', 'verbose_name_plural': 'Order Notes'},
        ),
    ]
