# Generated by Django 5.1.2 on 2024-11-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
