# Generated by Django 5.1.2 on 2024-12-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_invoice_stripe_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['due_on']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
