# Generated by Django 5.1.2 on 2024-12-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_invoice_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='stripe_pid',
            field=models.CharField(default=None, max_length=254),
        ),
    ]
